language: generic

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - gettext
    - libunwind8
    - libicu52
language: node_js
node_js:
- "4"

before_install:
- sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
- sudo apt-get update
- sudo apt-get -y install dotnet-dev-1.0.0-preview2-003121
- sudo apt-get -y install dotnet-hostfxr-1.0.2

env:
- DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
- dotnet restore
- dotnet publish --configuration Release --output artifacts/approot src/app
- dotnet publish --output artifacts ui
