version: '0.1.{build}'
configuration:
- Debug
platform: Any CPU
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- dotnet restore
- dotnet build src/app/project.json
- npm install --prefix ui
- ui/node_modules/.bin/bower install --config.cwd=ui
- ui/node_modules/.bin/typings install --cwd ui
- ui/node_modules/.bin/gulp --cwd ui
test_script:
- dotnet test test/app.tests
- Add-AppveyorMessage "Dotnet unit tests completed."
- ui/node_modules/.bin/karma start ui/karma.conf.js
- Add-AppveyorMessage "Typescript/javascript unit tests completed."
artifacts:
- path: src\app\bin\Debug\netcoreapp1.0
  name: approot
  type: zip
- path: ui\wwwroot
  name: webroot
  type: zip
cache:
- '%USERPROFILE%\.nuget\packages'
- 'ui\node_modules'
- 'ui\bower_components'
- 'ui\typings'
