version: '0.1.{build}'
environment:
    nodejs_version: "6.7"
    JSPM_GITHUB_AUTH_TOKEN:
        secure: iQJv6hQfYn6ykJpUPhNSnEcKJBMP1WKynxm70Xqdr3cOGdkLU06VFfRFmOvJwx58
    typings_githubToken:
        secure: iQJv6hQfYn6ykJpUPhNSnEcKJBMP1WKynxm70Xqdr3cOGdkLU06VFfRFmOvJwx58
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
- ps: Install-Product node $env:nodejs_version

build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- dotnet restore
- dotnet build src\app\project.json

- cd %APPVEYOR_BUILD_FOLDER%\ui
- npm install
- node_modules\.bin\jspm install
- node_modules\.bin\typings install
- node_modules\.bin\gulp

test_script:
- cd %APPVEYOR_BUILD_FOLDER%
- dotnet test test\app.tests
- npm install karma-coverage karma-sourcemap-loader karma-appveyor-reporter --prefix ui
- ui\node_modules\.bin\karma start ui\karma-appveyor.conf.js

after_test:
- cd %APPVEYOR_BUILD_FOLDER%
- nuget install OpenCover -Version 4.6.519 -o .\packages
- npm install codecov remap-istanbul
- packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:dotnet.exe -targetargs:"test test\app.tests" -register:user -oldstyle -filter:"+[HelloCoreClrApp*]* -[HelloCoreClrApp*.Tests*]*" -hideskipped:Filter -mergeoutput -output:reports\coverage-dotnet.xml
- node_modules\.bin\remap-istanbul -i reports\coverage-js.json -o reports\coverage-ts.json -t json
- node_modules\.bin\codecov --disable=gcov -f reports\coverage-dotnet.xml
- node_modules\.bin\codecov --disable=gcov -f reports\coverage-ts.json

cache:
- '%USERPROFILE%\.nuget\packages -> appveyor.yml'
- 'ui\node_modules -> appveyor.yml'
- 'ui\src\jspm_packages -> appveyor.yml'
- 'ui\typings -> appveyor.yml'
- 'node_modules -> appveyor.yml'
- 'packages -> appveyor.yml'
