version: '0.1.{build}'
environment:
    nodejs_version: "6"
    JSPM_GITHUB_AUTH_TOKEN:
        secure: iQJv6hQfYn6ykJpUPhNSnEcKJBMP1WKynxm70Xqdr3cOGdkLU06VFfRFmOvJwx58
    typings_githubToken:
        secure: iQJv6hQfYn6ykJpUPhNSnEcKJBMP1WKynxm70Xqdr3cOGdkLU06VFfRFmOvJwx58
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
- ps: Install-Product node $env:nodejs_version

build_script:
- dotnet restore
- dotnet build src\app\project.json

- cd %APPVEYOR_BUILD_FOLDER%\ui
- npm install
- node_modules\.bin\jspm install
- node_modules\.bin\typings install
- node_modules\.bin\gulp

before_test:
- cd %APPVEYOR_BUILD_FOLDER%
- nuget install OpenCover -Version 4.6.519 -o .\packages
- npm install karma-appveyor-reporter --prefix ui

test_script:
- packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:dotnet.exe -targetargs:"test test\app.tests" -register:user -oldstyle -filter:"+[HelloCoreClrApp*]* -[HelloCoreClrApp*.Tests*]*" -hideskipped:Filter -mergeoutput -output:reports\coverage-dotnet.xml
- ui\node_modules\.bin\karma start ui\karma.conf.js --reporters progress,coverage,remap-coverage,appveyor

after_test:
- npm install codecov
- node_modules\.bin\codecov --disable=gcov -f reports\coverage-dotnet.xml
- node_modules\.bin\codecov --disable=gcov -f reports\coverage-ts.json

cache:
- '%USERPROFILE%\.nuget\packages -> appveyor.yml'
- 'ui\node_modules -> appveyor.yml'
- 'ui\src\jspm_packages -> appveyor.yml'
- 'ui\typings -> appveyor.yml'
- 'node_modules -> appveyor.yml'
- 'packages -> appveyor.yml'
